# https://hub.docker.com/search?q=opencv&type=image
# https://hub.docker.com/r/jjanzic/docker-python3-opencv/dockerfile
version: 2.0
jobs:
  build:
    docker:
      - image: jjanzic/docker-python3-opencv:opencv-4.0.1
      - image: jjanzic/docker-python3-opencv:opencv-3.2.0
    working_directory: ~/work
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: cmake . && make